version: 2
updates:
- package-ecosystem: nuget
  directory: "/Rebus.RabbitMq"
  schedule:
    interval: daily
    time: "04:00"
- package-ecosystem: nuget
  directory: "/Rebus.RabbitMq.Tests"
  schedule:
    interval: daily
    time: "04:00"
