name: .NET Windows

on:
  push:
    branches: [ master,net50 ]
  pull_request:
    branches: [ master,net50 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install rabbitmq
      shell: pwsh
      run: choco install rabbitmq -Version 3.8.5
    - name: Restore dependencies
      run:  |
        dotnet nuget locals all --clear
        dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test Rebus.RabbitMq.Tests --no-build --verbosity normal -c Release
